#!/usr/bin/env python3
"""
Enrollment: learn stable cells from captured dumps, build fuzzy-extractor
helper data, and emit firmware/Core/Inc/helper_data.h.

  python enroll.py --dir captures --addr 20020000 --out ../firmware/Core/Inc/helper_data.h

The learning step (per-cell stability estimation + selection) is validated on
HELD-OUT captures that were not used for enrollment.
"""
import argparse, glob, hashlib
import numpy as np

N, KEY_BITS = 15, 256
SEL_BITS = N * KEY_BITS            # 3840
BITS = 32768

def load(d, addr):
    files = sorted(glob.glob(f"{d}/dump_{addr}_*.bin"))
    if not files:
        raise SystemExit("no dumps found")
    return np.array([np.unpackbits(np.fromfile(f, dtype=np.uint8), bitorder="little")
                     for f in files])

def h(tag, data):
    return hashlib.sha256(tag + data).digest()

def select_cells(train, rng):
    p1 = train.mean(axis=0)
    score = np.abs(p1 - 0.5) + rng.random(train.shape[1]) * 1e-6   # random tie-break
    idx = np.sort(np.argsort(-score)[:SEL_BITS])
    ref = (p1[idx] > 0.5).astype(np.uint8)
    return idx, ref, np.minimum(p1[idx], 1 - p1[idx])

def enroll(train, rng, secret):
    idx, ref, flip = select_cells(train, rng)
    s_bits = np.unpackbits(np.frombuffer(secret, dtype=np.uint8), bitorder="little")
    codeword = np.repeat(s_bits, N)
    helper = ref ^ codeword
    key = h(b"PUF-KEY-v1", secret)
    check = h(b"PUF-CHK-v1", key)
    return idx, helper, key, check, flip

def reconstruct(bits, idx, helper):
    w = bits[idx] ^ helper
    ones = w.reshape(KEY_BITS, N).sum(axis=1)
    s_bits = (ones > N // 2).astype(np.uint8)
    errs = np.where(s_bits == 1, N - ones, ones)
    return np.packbits(s_bits, bitorder="little").tobytes(), int(errs.sum()), int(errs.max())

def fingerprint(key):
    return hashlib.sha256(b"PUF-FP" + key).digest()[:4].hex()

def c_array(name, data, per=12):
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i+per]) for i in range(0, len(data), per)]
    return f"static const uint8_t {name}[{len(data)}] = {{\n  " + ",\n  ".join(rows) + "\n};\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="captures")
    ap.add_argument("--addr", default="20020000")
    ap.add_argument("--out", default="helper_data.h")
    ap.add_argument("--holdout", type=float, default=0.3, help="fraction held out for validation")
    ap.add_argument("--seed", type=int, default=None, help="reproducible run (testing only)")
    a = ap.parse_args()

    D = load(a.dir, a.addr)
    n = len(D)
    if D.shape[1] != BITS:
        raise SystemExit(f"expected {BITS} bits per dump, got {D.shape[1]}")
    if n < 20:
        print(f"WARNING: only {n} captures; use >= 50 for a trustworthy stability estimate")
    rng = np.random.default_rng(a.seed)

    # ---- validation: enroll on a training split, test on unseen boots ----
    k = max(2, int(round(n * (1 - a.holdout))))
    train, test = D[:k], D[k:]
    if len(test):
        secret = rng.bytes(32)
        idx, helper, key, check, flip = enroll(train, rng, secret)
        results = [reconstruct(t, idx, helper) for t in test]
        ok = sum(h(b"PUF-CHK-v1", h(b"PUF-KEY-v1", r[0])) == check for r in results)
        print(f"[validation] enrolled on {k} boots, tested on {len(test)} unseen boots")
        print(f"[validation] key reconstruction success: {ok}/{len(test)}")
        print(f"[validation] corrected bit errors / boot: mean {np.mean([r[1] for r in results]):.1f}, "
              f"max {max(r[1] for r in results)}  (of {SEL_BITS})")
        print(f"[validation] worst group errors: {max(r[2] for r in results)} (fails at >= {N//2 + 1})")
        print(f"[validation] selected-cell BER on unseen boots: "
              f"{np.mean([(t[idx] != (train.mean(0)[idx] > .5)).mean() for t in test]):.4f}")
        if ok != len(test):
            print("[validation] FAILURES: collect more captures or increase N.")

    # ---- final enrollment on ALL captures -------------------------------
    secret = rng.bytes(32) if a.seed is not None else __import__("os").urandom(32)
    idx, helper, key, check, flip = enroll(D, rng, secret)
    mask = np.zeros(BITS, dtype=np.uint8); mask[idx] = 1
    print(f"[enroll] selected {SEL_BITS} cells, max observed flip prob {flip.max():.3f}, "
          f"mean {flip.mean():.4f}")
    print(f"[enroll] KEY FINGERPRINT (device should print this): {fingerprint(key)}")

    with open(a.out, "w") as f:
        f.write("/* GENERATED by host/enroll.py - public helper data, no secrets. */\n")
        f.write("#ifndef HELPER_DATA_H\n#define HELPER_DATA_H\n#include <stdint.h>\n")
        f.write("#define PUF_ENROLLED 1\n")
        f.write(c_array("PUF_SEL_MASK", np.packbits(mask, bitorder="little").tobytes()))
        f.write(c_array("PUF_HELPER", np.packbits(helper, bitorder="little").tobytes()))
        f.write(c_array("PUF_KEYCHECK", check))
        f.write("#endif\n")
    print(f"[enroll] wrote {a.out}")

if __name__ == "__main__":
    main()
